# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard_3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wizard_3(object):
    def setupUi(self, wizard_3):
        wizard_3.setObjectName("wizard_3")
        wizard_3.resize(650, 440)
        wizard_3.setMinimumSize(QtCore.QSize(650, 440))
        wizard_3.setMaximumSize(QtCore.QSize(650, 440))
        self.frame_4 = QtWidgets.QFrame(wizard_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 650, 440))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.uberschriftLabel = QtWidgets.QLabel(self.frame_4)
        self.uberschriftLabel.setGeometry(QtCore.QRect(0, 20, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uberschriftLabel.setFont(font)
        self.uberschriftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.uberschriftLabel.setObjectName("uberschriftLabel")
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setGeometry(QtCore.QRect(0, 370, 650, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalFrame_4 = QtWidgets.QFrame(self.frame_4)
        self.horizontalFrame_4.setGeometry(QtCore.QRect(0, 80, 656, 301))
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.abweichungLabel = QtWidgets.QLabel(self.horizontalFrame_4)
        self.abweichungLabel.setGeometry(QtCore.QRect(260, 0, 130, 44))
        self.abweichungLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.abweichungLabel.setFont(font)
        self.abweichungLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.abweichungLabel.setLineWidth(1)
        self.abweichungLabel.setObjectName("abweichungLabel")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_5.setGeometry(QtCore.QRect(490, 10, 123, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 82, 24))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_7.setGeometry(QtCore.QRect(170, 0, 30, 40))
        self.label_7.setMaximumSize(QtCore.QSize(30, 40))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../icons/Pfeil_transparent_small.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_10.setGeometry(QtCore.QRect(430, 0, 30, 40))
        self.label_10.setMaximumSize(QtCore.QSize(30, 40))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../icons/Pfeil_transparent_small.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(407, 75, 180, 27))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_3.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(412, 140, 180, 27))
        self.lineEdit_7.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_7.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.line_6 = QtWidgets.QFrame(self.horizontalFrame_4)
        self.line_6.setGeometry(QtCore.QRect(-13, 101, 781, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.horizontalFrame_4)
        self.line_7.setGeometry(QtCore.QRect(-5, 176, 781, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.horizontalFrame_4)
        self.verticalScrollBar.setGeometry(QtCore.QRect(629, 54, 20, 241))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_4.setGeometry(QtCore.QRect(405, 51, 189, 21))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_9.setGeometry(QtCore.QRect(412, 115, 211, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(414, 204, 180, 27))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label.setGeometry(QtCore.QRect(55, 132, 169, 21))
        self.label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalFrame_4)
        self.lineEdit.setGeometry(QtCore.QRect(56, 204, 180, 27))
        self.lineEdit.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_4)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 109, 21))
        self.label_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(325, 130, 20, 248))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setGeometry(QtCore.QRect(-103, 67, 871, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.zuruckButton = QtWidgets.QPushButton(self.frame_4)
        self.zuruckButton.setEnabled(True)
        self.zuruckButton.setGeometry(QtCore.QRect(380, 390, 120, 30))
        self.zuruckButton.setCheckable(False)
        self.zuruckButton.setObjectName("zuruckButton")
        self.weiterButton = QtWidgets.QPushButton(self.frame_4)
        self.weiterButton.setGeometry(QtCore.QRect(520, 390, 120, 30))
        self.weiterButton.setObjectName("weiterButton")
        self.line_5 = QtWidgets.QFrame(self.frame_4)
        self.line_5.setGeometry(QtCore.QRect(0, 122, 650, 16))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")

        self.retranslateUi(wizard_3)
        QtCore.QMetaObject.connectSlotsByName(wizard_3)

    def retranslateUi(self, wizard_3):
        _translate = QtCore.QCoreApplication.translate
        wizard_3.setWindowTitle(_translate("wizard_3", "Form"))
        self.uberschriftLabel.setText(_translate("wizard_3", "Abweichenung \"mehr Druck\" in Knoten Nr. D-1"))
        self.abweichungLabel.setText(_translate("wizard_3", "mehr Druck    "))
        self.label_5.setText(_translate("wizard_3", "Konsequenz"))
        self.label_2.setText(_translate("wizard_3", "Ursache"))
        self.lineEdit_3.setText(_translate("wizard_3", "1.2. weitere..."))
        self.lineEdit_7.setText(_translate("wizard_3", "2.2. weitere..."))
        self.label_4.setText(_translate("wizard_3", "1.1 Schaden am Ventil V1"))
        self.label_9.setText(_translate("wizard_3", "2.1 Schaden an Sensor K2"))
        self.lineEdit_2.setText(_translate("wizard_3", "3. weitere..."))
        self.label.setText(_translate("wizard_3", "2. zu hohe Temperatur"))
        self.lineEdit.setText(_translate("wizard_3", "3. weitere..."))
        self.label_3.setText(_translate("wizard_3", "1. zu viel Fluss"))
        self.zuruckButton.setText(_translate("wizard_3", "Zurück"))
        self.weiterButton.setText(_translate("wizard_3", "Weiter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wizard_3 = QtWidgets.QWidget()
    ui = Ui_wizard_3()
    ui.setupUi(wizard_3)
    wizard_3.show()
    sys.exit(app.exec_())
