# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wizard_1(object):
    def setupUi(self, wizard_1):
        wizard_1.setObjectName("wizard_1")
        wizard_1.resize(648, 434)
        self.frame = QtWidgets.QFrame(wizard_1)
        self.frame.setGeometry(QtCore.QRect(0, 0, 681, 451))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 0, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(270, 140, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textFeld = QtWidgets.QTextEdit(self.frame)
        self.textFeld.setGeometry(QtCore.QRect(270, 180, 331, 41))
        self.textFeld.setObjectName("textFeld")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 90, 332, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(370, 370, 251, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.zurckButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.zurckButton.setEnabled(False)
        self.zurckButton.setCheckable(False)
        self.zurckButton.setObjectName("zurckButton")
        self.horizontalLayout.addWidget(self.zurckButton)
        self.weiterButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.weiterButton.setObjectName("weiterButton")
        self.horizontalLayout.addWidget(self.weiterButton)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 360, 641, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(wizard_1)
        QtCore.QMetaObject.connectSlotsByName(wizard_1)

    def retranslateUi(self, wizard_1):
        _translate = QtCore.QCoreApplication.translate
        wizard_1.setWindowTitle(_translate("wizard_1", "Form"))
        self.label.setText(_translate("wizard_1", "Definieren Sie die Parameter für Knoten X."))
        self.label_2.setText(_translate("wizard_1", "Parameter hinzufügen:"))
        self.checkBox_3.setText(_translate("wizard_1", "Druck"))
        self.checkBox_5.setText(_translate("wizard_1", "Temperatur"))
        self.checkBox_6.setText(_translate("wizard_1", "Füllstand"))
        self.checkBox_4.setText(_translate("wizard_1", "Fluss"))
        self.checkBox_2.setText(_translate("wizard_1", "Unreinheiten"))
        self.checkBox.setText(_translate("wizard_1", "Isolation"))
        self.checkBox_7.setText(_translate("wizard_1", "hier muss noch irgendwie generierter hin"))
        self.zurckButton.setText(_translate("wizard_1", "Zurück"))
        self.weiterButton.setText(_translate("wizard_1", "Weiter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wizard_1 = QtWidgets.QWidget()
    ui = Ui_wizard_1()
    ui.setupUi(wizard_1)
    wizard_1.show()
    sys.exit(app.exec_())
